"""Create User2 

Revision ID: 2044d7ad0037
Revises: b4fe08ff930f
Create Date: 2024-03-24 17:34:50.977670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2044d7ad0037"
down_revision: Union[str, None] = "b4fe08ff930f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records", sa.Column("title", sa.String(length=30), nullable=False)
    )
    op.add_column(
        "records",
        sa.Column("body", sa.Text(), server_default="", nullable=False),
    )
    op.add_column(
        "records", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "records", "users", ["user_id"], ["id"])
    op.drop_column("records", "text")
    op.drop_column("records", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("name", sa.VARCHAR(), nullable=False))
    op.add_column("records", sa.Column("text", sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, "records", type_="foreignkey")
    op.drop_column("records", "user_id")
    op.drop_column("records", "body")
    op.drop_column("records", "title")
    # ### end Alembic commands ###
